### PR TITLE
Article Footnote block

### LINKED ISSUE #143: `Footnote` Block
The current news.sap.com has the option to select s-m-l for font size.
Where we encounter "s", this we translate to a `Footnote` block that is styled accordingly as most know pages all use this at the end of the content area as footnote section
the alternative would have been to use sections and section metadata, but we want to use sections for other purposes.

see also https://github.com/users/urfuwo/projects/1/views/1?pane=issue&itemId=53843510

- [x] Import
- [ ] Block implementation

Figma Reference: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1661-87908&mode=design&t=evGziGhVZ935Alot-4

Image

### PR DESCRIPTION
**Pull request by larsauffarth**
Fix #143

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/news/0000/the-article
- After: https://143-footnote-block--hlx-test--urfuwo.hlx.page/news/0000/the-article
- Test 2: https://143-footnote-block--hlx-test--urfuwo.hlx.page/news/2024/02/sap-further-strengthens-ai-focus-dedicated-growth-area

- [x] New Blocks introduced in this PR

Block Name    | Documentation | Library Link
------------- | -------------|----------------
article-footnote | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/doc.aspx?sourcedoc=%7B02046f1e-8c45-40a3-b153-44cb88e40bdd%7D&action=edit) | [Library Link](https://143-footnote-block--hlx-test--urfuwo.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/article-footnote&index=0)

- [ ] New variations introduced in this PR

### CODE REVIEW

**Comment by mhaack** [comment]
@larsauffarth code looks good, but I adjusted the block name to `Article Footnote` to align with the other `Artilce ...` blocks and have a clear indication this block is for L3 article pages. Please adjust. Another good test URL is https://main--hlx-test--urfuwo.hlx.page/news/2024/02/sap-further-strengthens-ai-focus-dedicated-growth-area

**Comment by larsauffarth** [comment]
@mhaack I see that for the-article page the footnote class is still added like this: `<div class="footnote">`
Just to double check, will this change to `article-footnote` as well?

**Comment by mhaack** [comment]
Sorry, I changed it but forgot to publish 🤦 fixed now. This is how the block should look like:

`+-----------------------------------------------------------------------------------------------------------------------+
| **Article Footnote**                                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------+
| Footnote / Annotation lorem ipsum dolor sit amet consectetur. Pharetra lorem viverra neque viverra mauris aliquam ac. |
| diam enim nibh.                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------+
`

**Comment by larsauffarth** [comment]
@mhaack thanks for the clarification! Name change is done.

**Review by mhaack — APPROVED** [review]
LGTM

**Pull request merged**
