### PR TITLE
421: Hero variant with subheading

### LINKED ISSUE #421: Hero Variant with Subheading
For the sap.com/design pages we need additional hero variant which has following elements:
1. Eyebrow
2. Heading
3. Sub heading
4. Text
5. CTA
6. Background image/background color
Existing Hero variants do not have option for sub heading.

Screenshot 2024-04-04 at 14 05 45

### PR DESCRIPTION
**Pull request by rjwtrmn**
Added new justify class for hero, to force heading and content to top and bottom of hero respectively
Adjusted typography to match designs

Fix #421

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/design/about
- After: https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/design/about

L3 (Typography changed)
- Before: https://main--hlx-test--urfuwo.hlx.live/resources/the-circular-economy-goes-mainstream
- After: https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/resources/the-circular-economy-goes-mainstream

L1 (Typography changed)
- Before: https://main--hlx-test--urfuwo.hlx.live/topics
- After: https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/topics

L2 (Typography changed)
- Before: https://main--hlx-test--urfuwo.hlx.live/topics/ai
- After: https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/topics/ai

### CODE REVIEW

**Comment by saurabh-khare** [comment]
@rjwtrmn Can you add a subheading here?
https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/design/
Screenshot 2024-04-05 at 10 46 03

**Comment by rjwtrmn** [comment]
> @rjwtrmn Can you add a subheading here? https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/design/ Screenshot 2024-04-05 at 10 46 03

Switched to use an example page with a subheading, forgot that this page doesn't need one

**Comment by saurabh-khare** [comment]
> > @rjwtrmn Can you add a subheading here? https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/design/ Screenshot 2024-04-05 at 10 46 03
> 
> @saurabh-khare Switched to use an example page with a subheading, forgot that this page doesn't need one

Ok, can we ensure if theres no subheading we do not leave vertical space empty?

**Comment by rjwtrmn** [comment]
> > > @rjwtrmn Can you add a subheading here? https://421-hero-variant-with-subheading--hlx-test--urfuwo.hlx.live/design/ Screenshot 2024-04-05 at 10 46 03
> > 
> > 
> > @saurabh-khare Switched to use an example page with a subheading, forgot that this page doesn't need one
> 
> Ok, can we ensure if theres no subheading we do not leave vertical space empty?

But the design calls for space even if there is no subheading it https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=5778-55366&mode=design&t=lo9MPzRIMaHWTjbk-0

**Pull request merged**
