### PR TITLE
250 and 251: author, topic and tag pages

### LINKED ISSUE #250: Author, topic and tag pages
Update: Added topic and tag pages from #251

Author Pages (#250):

1. Non-curated author pages: create author template page (best-effort), make sure it looks good
2. Curated author pages: check curated author pages and make sure these align with curated author pages in figma, e.g. the Julia White Example https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65739&mode=design&t=zbCbmMnKpNcTu4NN-4 (3 examples are sufficient)

Topic and Tag Pages (from #251):

Figma doesn't currently include an example of a non-curated Topic Page.
An example would be https://main--hlx-test--urfuwo.hlx.page/topics/ai which is currently off in terms of styling.

Tasks:

- create a template that is a reasonable representation for non-curated Topic Pages (authoring team can later change the template, just needs to look OK)

- create shared side navigation for 2 sample topic groups and map that side navigation through the metadata sheet

- use topic group sustainbability, sub topics of green software development, carbon accounting for an example

all other topics don't use a side navigation (meaning L2 needs to work without a side nav)

### LINKED ISSUE #251: Non-curated L2 Topic and Tag Pages
Figma doesn't currently include an example of a non-curated Topic Page.
An example would be https://main--hlx-test--urfuwo.hlx.page/topics/ai which is currently off in terms of styling.

Tasks:
1. create a template that is a reasonable representation for non-curated Topic Pages (authoring team can later change the template, just needs to look OK)

2. create shared side navigation for 2 sample topic groups and map that side navigation through the metadata sheet
- use topic group sustainbability, sub topics of green software development, carbon accounting for an example 
- all other topics don't use a side navigation (meaning L2 needs to work without a side nav)

### PR DESCRIPTION
**Pull request by pahupe**
fix: non-curated and curated author pages (#250)
fix: non-curated and curated topic and tag pages (#251)

Author Pages - four examples:
- Curated, full author page, custom sidebar ("Julia White"): https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/author/juliawhite
- Curated, full author page, no sidebar: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/author/scottrussell
- Curated, simple author profile, default author sidebar ("Primary Contributors"): https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/author/luistrunkdeflores
- Non-curated, dynamically generated author page: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/author/jacquelineprause

Topic pages:
- Non-curated topic page, fallback sidenav: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/ai
- Non-curated topic page, custom sidenav (sustainability): https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/sustainability
- Curated topic page, no sidenav: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/cloud

Tag pages:
- Non-curated tag page, fallback sidenav: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/tags/generative-ai
- Curated tag page, no sidenav: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/tags/customer-story

NOTE: None of the author pages render as expected (at least for me), despite having published the pages and the author index:
- Julia and Scott still show "#250" in their hero title despite it not being part of the published content
- Luis: sidebar does not show, despite having a sidebar
- Jacqueline: sidebar is not showing; title banner is not rendered correctly (should render the same way as for Luis)
See https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1710229078307869

Content changes:
- The curated, full author profile pages (Julia, Scott) no longer use a 2-column block as their "hero", but use a "fixed height" hero banner. Ref: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65896&mode=design&t=6itSVsRU7i2lvGCz-4 
- Consequence: #248 must be implemented
- Author, topic and tag page templates have been updated
- Sidenav pages have been added to author, topics and tags folder

Default vs override:
- Default for L2 pages is: there is a side nav per default (default as required by design team); pages can choose to have no sidenav

Fix #250
Fix #251

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/author/juliawhite
- After: https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/author/juliawhite

### CODE REVIEW

**Comment by mhaack** [comment]
@pahupe with #270 the `Title Banner (author)` block should go away and replaced by a hero. WDYT?

**Comment by pahupe** [comment]
> @pahupe with #270 the `Title Banner (author)` block should go away and replaced by a hero. WDYT?

@mhaack: Fine with me. On the "full author profile" pages like Julia White and Scott Russell, I had replaced the existing Columns block with a Hero, see
- https://sap.sharepoint.com/:w:/r/sites/207899/Shared%20Documents/website/author/scottrussell.docx?d=w52e5bcc3bcb441ce96325c7dec3bcd6d&csf=1&web=1&e=oCYV2u
- https://sap.sharepoint.com/:w:/r/sites/207899/Shared%20Documents/website/author/juliawhite.docx?d=w8fe751ded3594b3a8447df411477910e&csf=1&web=1&e=dMVL4x 

I am fine to also remove the Title Banner on the "limited profile" and "dynamically generated" (author template) author pages.

**Comment by pahupe** [comment]
> @pahupe with #270 the `Title Banner (author)` block should go away and replaced by a hero. WDYT?

@mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages

**Comment by benpeter** [comment]
> > @pahupe with #270 the `Title Banner (author)` block should go away and replaced by a hero. WDYT?
> 
> @mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages

@pahupe @mhaack why not use a Hero? I don't think "Title Banner" is something that exists, it was more of a placeholder before we knew better

**Comment by mhaack** [comment]
> @mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages

@pahupe why?

**Comment by pahupe** [comment]
> > @mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages
> 
> @pahupe why?

@mhaack : I suggest to do that in a separate ticket: Let's complete this PR so we have the layout for the current content fixed, and then let's address the content replacement (title banner => hero) separately. What do you think?

**Comment by benpeter** [comment]
> > > @mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages
> > 
> > 
> > @pahupe why?
> 
> @mhaack : I suggest to do that in a separate ticket: Let's complete this PR so we have the layout for the current content fixed, and then let's address the content replacement (title banner => hero) separately. What do you think?

@pahupe why? it's just 2 or 3 word docs, right?

**Comment by pahupe** [comment]
> > > > @mhaack : But let's not throw away the Title Banner block, as we still need it for Topic and Tag pages
> > > 
> > > 
> > > @pahupe why?
> > 
> > 
> > @mhaack : I suggest to do that in a separate ticket: Let's complete this PR so we have the layout for the current content fixed, and then let's address the content replacement (title banner => hero) separately. What do you think?
> 
> @pahupe why? it's just 2 or 3 word docs, right?

@mhaack , @benpeter :
- Happy to replace the title banner / column block on all "full author" pages like Julia White, Scott Russell, Christian Klein, etc. with a Hero. Some of this has actually already been done, see e.g., https://hero-2--hlx-test--urfuwo.hlx.live/author/juliawhite. I would assume more content rework for the other "full author" pages can be done if needed, but independently of this PR, as it is content work
- We can also see if we use a Hero on the dynamically generated author pages. I suggest to do that content rework separately from this PR. Also, we need this caching issue addressed: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1710229078307869
- For tags and topics dynamic pages, we currently use the title banner custom logic to extract a displayable title, see code in title-banner.js. I don't think this can be achieved simply by using placeholders, so some of that logic would end up in the hero component. We could do that, but I propose to do that in a separate ticket
- In general: we now (6 days before Mid-March) have a solution where we can showcase heros on author pages (https://hero-2--hlx-test--urfuwo.hlx.live/author/juliawhite) and topic pages (https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/cloud). I would put the title-banner => hero replacement task into a separate ticket, and if it fits before Mid-March, let's tackle it, or else later

**Comment by mhaack** [comment]
@pahupe do you want to rebase this on main first. Also please double check the LHS check, the dynamic pages look like constantly not getting 100?

**Comment by pahupe** [comment]
> @pahupe do you want to rebase this on main first. Also please double check the LHS check, the dynamic pages look like constantly not getting 100?

@mhaack : 
- Rebased onto main, looks good.
- Also, I replaced the hlx.page URLs with hlx.live. The pages that score slightly worse than the others are https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/sustainability and https://250-non-curated-author-pages--hlx-test--urfuwo.hlx.live/topics/ai, and I assume this is due to the fact that we have a long list of articles for these topics. We would have to address this by limiting the entries loaded and rendered by 'article list'

**Comment by mhaack** [comment]
I think, after conflicts are merged this is good to merge.

**Review by mhaack — APPROVED** [review]

**Pull request merged**
