### PR TITLE
Section Styles (background colors, divider) iteration 1

### LINKED ISSUE #153: section styles
Goal: visual dividers should be implemented as borders on sections (defaulting to top)
background styling in section metadata (variants to be determined from Figma / with Dani and Elaine).

For this, use section metadata, as can be found in /news/0000/the-article-new.docx

figma samples for background styling
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65943&mode=design&t=evGziGhVZ935Alot-4
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65509&mode=design&t=evGziGhVZ935Alot-4
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-66390&mode=design&t=evGziGhVZ935Alot-4

figma sample for dividers
https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65931&mode=design&t=evGziGhVZ935Alot-4

Image

Image

Image

### PR DESCRIPTION
**Pull request by pahupe**
Added section styles, based on #182

Fix #153

Examples see /draft/hupe/the-article-new.docx section styles:
- Background Blue | Blue/1 | Blue/2 | Blue/3 | Green | Green/1 | Green/2 | Pink | Pink/1 | Pink/2 (selection from: https://sap.frontify.com/document/223141#/identity/color/primary-palette)
- Text White | Black (ref: https://sap.frontify.com/document/223141#/identity/color/primary-palette)
- Divider Top (ref: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65935&mode=design&t=f9a81Y185XdjuZd4-4 > above this element and its header)
- Row Wide (temporary CSS style to better distinguish normal/narrow rows from wide rows, see L2 designs)

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/blog/
- After: https://153-section-metadata--hlx-test--urfuwo.hlx.page/blog/

### CODE REVIEW

**Comment by mhaack** [comment]
Looks off to me
Screenshot 2024-02-28 at 09 28 02

**Comment by pahupe** [comment]
@mhaack : Difficult to say what exactly is "off".
The divider is a single px line surrounded (top/bottom) by 2px of white space (see here: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=2175-111922&mode=design&t=FBPHPReXFfM1FtLa-4 > above "All Press..."). It is followed by a section with a vertical spacing of 56px from the section's top to the first element (the headline) in the section.

Normally, one wouldn't combine top divider and a colored background, but use either or. Better see this sample section: https://153-section-metadata--hlx-test--urfuwo.hlx.page/draft/hupe/the-article-new > "Another section [section style: divider on top]" (which does not have a colored background.
Also, the left / right margins are off (for the entire body grid area), which make the divider look "pushed to the left", but that would have to be fixed in the page grid.

**Comment by pahupe** [comment]
Section styles (background color, divider) have been included in the hub template, as they are currently not required on L3 / article pages, only on hub pages (side note: the article footnote block on L3 pages brings its own divider). If this changes, section styles can be moved into their own CSS file.

**Comment by pahupe** [comment]
Also note: @urfuwo wants to introduce a level of indirection for the background color keys. This will be addressed in a separate ticket when the final keys are known.

**Review by benpeter — APPROVED** [review]

**Review by saurabh-khare — APPROVED** [review]

**Pull request merged**
