### PR TITLE
Cards block: add breakpoints, icons variant, grid-n-column variant

### LINKED ISSUE #264: Cards block with small and icons and n-columns variants
Based on https://github.com/adobe/aem-boilerplate/tree/main/blocks/cards
Also add a "Small" variant with smaller cards (4 in a row)

Screenshot 2024-03-12 at 14 18 14
Screenshot 2024-03-12 at 14 17 54

### PR DESCRIPTION
**Pull request by rootpea**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #264 

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page
- After: https://264-cards--hlx-test--urfuwo.hlx.page/draft/rootpea/219-l1-sample-page

- [ ] New Blocks introduced in this PR

- [x] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. hero (light)  | [doc-link](https://sap.sharepoint.com/:w:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B0B62F23A-5C8F-4C2D-BA2E-C444D3631B51%7D&file=hero.docx&action=default&mobileredirect=true)

### CODE REVIEW

**Comment by mhaack** [comment]
For the use case I think we need an `Cards (icons)` option here to get some styles for the specific version with the icons to get these in same size & position.

**Comment by rootpea** [comment]
> For the use case I think we need an `Cards (icons)` option here to get some styles for the specific version with the icons to get these in same size & position.

which size and position?

**Comment by mhaack** [comment]
These icons have different size and are not aligned with the text.

Screenshot 2024-03-15 at 09 26 55

**Comment by rootpea** [comment]
> These icons have different size and are not aligned with the text.

fixed, thanks

**Comment by mhaack** [comment]
👍 Icons looking good now, but buttons are still unstyled. Is that done in seperate PR?

**Comment by rootpea** [comment]
> 👍 Icons looking good now, but buttons are still unstyled. Is that done in seperate PR?

yes in https://github.com/urfuwo/hlx-test/issues/268

**Review by mhaack — APPROVED** [review]

**Pull request merged**
