### PR TITLE
Sorting of content lists by recency (newest publication date first)

### LINKED ISSUE #211: content list iteration 2: sorting
Split-off from #149 

Context: Sorting requires stream-sorting in the underlying ffetch library, hence this has been extracted from #149. Details: (Meaningful) sorting and then result set limiting can only be implemented at the ffetch library level

Goal: Implement sorting by recency

### PR DESCRIPTION
**Pull request by pahupe**
fix: added sorting by recency to content lists only

Fix #211 

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications
- After: https://211-content-list-iteration-2-sorting--hlx-test--urfuwo.hlx.live/blog/2023/11/idc-marketscape-sap-a-leader-cloud-enabled-sourcing-applications

### CODE REVIEW

**Comment by pahupe** [comment]
@mhaack, @benpeter: We actually need to either sort in Excel or remove the ffetch limit. Otherwise we get a subset from ffetch which may or may not include the most recent entries (which we then sort). That's why I thought it would be best to change ffetch. You can't really use ffetch.limit() and then sort on it.

**Comment by benpeter** [comment]
the solution is to sort in Excel @pahupe  :)

**Comment by benpeter** [comment]
and thanks @mhaack - as usual in EDS the solution is too simple to find it :-D

**Comment by mhaack** [comment]
> You can't really use ffetch.limit() and then sort on it

Correct, hence sort at source aka. Excel und use .limit to fetch only the number of docs you need.

**Comment by saurabh-khare** [comment]
What if we want this block on different pages and all want different sort order? Sorting in excel will change the order everywhere.

**Comment by mhaack** [comment]
> Sorting in excel will change the order everywhere.
Yes. But we can have multiple sheets in the workbook with different rules applied.

**Comment by saurabh-khare** [comment]
> > Sorting in excel will change the order everywhere.
> > Yes. But we can have multiple sheets in the workbook with different rules applied.

Got it. So in the end we need on author's input for sheet name.

**Comment by mhaack** [comment]
> Got it. So in the end we need on author's input for sheet name.
Yes indirectly lets say via a "sorting" option. And only if we need a different sorting.

**Comment by benpeter** [comment]
> And only if we need a different sorting.
which for now we don't :)

**Comment by pahupe** [comment]
Ok, then agreed: the existing sheet will be sorted by recency (newest first) in Excel, and if we need other sorting options that will also be covered via Excel

**Pull request closed without merging**
