### PR TITLE
Align hero content with rest of the page

### LINKED ISSUE #220: Hero contents must align with the rest of the page content
The hero block must take full width as specified in L3 page specifications. However the contents inside must align with the page gutters. This is different from aligning whole hero block between the gutters as it will also shrink the hero background image which is not desirable. 

Current State:
Screenshot 2024-03-01 at 17 46 26

Desired:
Screenshot 2024-03-01 at 17 50 40

### PR DESCRIPTION
**Pull request by saurabh-khare**
Hacky way to restrict hero content. Ideally it must be done by slot variables but they do not expose padding/margins on all axis. 

Fix #220 

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo
- After: https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo

### CODE REVIEW

**Comment by mhaack** [comment]
code LGTM, check test 4 that does not align correct on the right side

**Comment by saurabh-khare** [comment]
> code LGTM, check test 4 that does not align correct on the right side

Thats background picture. We want full width background picture and background color for hero.

**Review by pahupe — CHANGES_REQUESTED** [review]
Sorry, I have found a few examples where the spacing does not work (all in XL):
https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo1 - in XL the hero is too wide (as is the footer)
https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo3 - same in XL
https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/author/juliawhite - here the hero does not take the full page width, but the left margin is computed as if it was taking the full width

**Comment by saurabh-khare** [comment]
> Sorry, I have found a few examples where the spacing does not work (all in XL): https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo1 - in XL the hero is too wide (as is the footer) https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/draft/mhaack/hero-demo3 - same in XL https://220-restrict-hero-content--hlx-test--urfuwo.hlx.live/author/juliawhite - here the hero does not take the full page width, but the left margin is computed as if it was taking the full width

Pls check now.

**Review by mhaack — APPROVED** [review]

**Review by pahupe — APPROVED** [review]
LGTM

**Pull request merged**
