### PR TITLE
173 video with placeholder image

### LINKED ISSUE #173: Video with Placeholder image
We need support for video (youtube) player with a placeholder image which are used on todays news pages.

This is implemented via the `embed` block we can take over from the block collection: https://www.aem.live/developer/block-collection/embed

Sample pages:
* https://main--hlx-test--urfuwo.hlx.page/blog/2023/07/standard-chartered-total-workforce-solution
* https://main--hlx-test--urfuwo.hlx.page/news/2023/11/sap-mercedes-amg-petronas-f1-team-join-forces-drive-efficiency

See Figma https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=699-32259&mode=design&t=oGjZrklt5hCErBMt-4

- [ ] Need "play" button icon
- [x] Import
- [ ] Embed Block impl/customization

### PR DESCRIPTION
**Pull request by mlangfordsap**
Fix #173

Test URLs:
- Before: https://main--hlx-test--urfuwo.hlx.live/draft/mlangford/standard-chartered-total-workforce-solution
- After: https://173-video-with-placeholder-image--hlx-test--urfuwo.hlx.live/draft/mlangford/standard-chartered-total-workforce-solution

Changes `scripts/script.js` to allow for multiple players rather than just YouTube.  In this case, LinkedIn, but introduces a configuration feature that can be extended.

### CODE REVIEW

**Review by benpeter — APPROVED** [review]
LGTM

**Comment by benpeter** [comment]
look into this one? 
https://pagespeed.web.dev/analysis/https-173-video-with-placeholder-image--hlx-test--urfuwo-hlx-page-draft-mlangford-standard-chartered-total-workforce-solution/9ah6lqdqbh?utm_source=psi&utm_medium=redirect&form_factor=mobile
image

**Comment by mlangfordsap** [comment]
> look into this one? https://pagespeed.web.dev/analysis/https-173-video-with-placeholder-image--hlx-test--urfuwo-hlx-page-draft-mlangford-standard-chartered-total-workforce-solution/9ah6lqdqbh?utm_source=psi&utm_medium=redirect&form_factor=mobile

Unfortunately, this uses external players which drag in a ton of external scripts.  It's one of the main reasons we don't allow these kinds of things on the .COM site (data privacy compliance is the other major one).  The LinkedIn player is particularly terrible.

On thing I note too is this test page loads two players - that's an unlikely use case.

This uses an intersection observer to only load the players when the user gets there (I'm not clear how the page speed scan handles that actually - does it execute those immediately or emulate a human scroll speed??), so at least the players aren't blocking ICP (in practical use anyway), but if using these players is a requirement, I'm not sure what else to do.   My original plan to use placeholder images so the user had to manually click/tap before player code was loaded would have been more performant I think, but that need changed.  I'd be open to suggestions to improve this, as I'm not sure what else can be done given the UX requirements.

**Comment by benpeter** [comment]
> > look into this one? https://pagespeed.web.dev/analysis/https-173-video-with-placeholder-image--hlx-test--urfuwo-hlx-page-draft-mlangford-standard-chartered-total-workforce-solution/9ah6lqdqbh?utm_source=psi&utm_medium=redirect&form_factor=mobile
> 
> Unfortunately, this uses external players which drag in a ton of external scripts. It's one of the main reasons we don't allow these kinds of things on the .COM site (data privacy compliance is the other major one). The LinkedIn player is particularly terrible.
> 
> On thing I note too is this test page loads two players - that's an unlikely use case.
> 
> This uses an intersection observer to only load the players when the user gets there (I'm not clear how the page speed scan handles that actually - does it execute those immediately or emulate a human scroll speed??), so at least the players aren't blocking ICP (in practical use anyway), but if using these players is a requirement, I'm not sure what else to do. My original plan to use placeholder images so the user had to manually click/tap before player code was loaded would have been more performant I think, but that need changed. I'd be open to suggestions to improve this, as I'm not sure what else can be done given the UX requirements.

Agree - let's proceed

**Pull request merged**
